/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ParentalControls = IDL.Record({
  'contentFilterEnabled' : IDL.Bool,
  'maxAgeRating' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'dob' : IDL.Int,
  'cameraVerification' : IDL.Bool,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'ageVerified' : IDL.Bool,
  'parentalControls' : ParentalControls,
  'verifiedAge' : IDL.Opt(IDL.Nat),
  'passwordHash' : IDL.Text,
});
export const UpdateUserProfileResponse = IDL.Variant({
  'wrongPassword' : IDL.Null,
  'usernameAlreadyExists' : IDL.Null,
  'registerNotFound' : IDL.Null,
  'success' : IDL.Null,
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'countUsers' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'isUsernameTaken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int],
      [UpdateUserProfileResponse],
      [],
    ),
  'removeUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateCameraVerification' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
  'updateDisplayName' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateParentalControls' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'updatePassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'verifyAge' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ParentalControls = IDL.Record({
    'contentFilterEnabled' : IDL.Bool,
    'maxAgeRating' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'dob' : IDL.Int,
    'cameraVerification' : IDL.Bool,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'ageVerified' : IDL.Bool,
    'parentalControls' : ParentalControls,
    'verifiedAge' : IDL.Opt(IDL.Nat),
    'passwordHash' : IDL.Text,
  });
  const UpdateUserProfileResponse = IDL.Variant({
    'wrongPassword' : IDL.Null,
    'usernameAlreadyExists' : IDL.Null,
    'registerNotFound' : IDL.Null,
    'success' : IDL.Null,
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'countUsers' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'isUsernameTaken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int],
        [UpdateUserProfileResponse],
        [],
      ),
    'removeUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateCameraVerification' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
    'updateDisplayName' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateParentalControls' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'updatePassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'verifyAge' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };