/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ParentalControls {
  'contentFilterEnabled' : boolean,
  'maxAgeRating' : bigint,
}
export type UpdateUserProfileResponse = { 'wrongPassword' : null } |
  { 'usernameAlreadyExists' : null } |
  { 'registerNotFound' : null } |
  { 'success' : null };
export interface UserProfile {
  'dob' : bigint,
  'cameraVerification' : boolean,
  'username' : string,
  'displayName' : string,
  'ageVerified' : boolean,
  'parentalControls' : ParentalControls,
  'verifiedAge' : [] | [bigint],
  'passwordHash' : string,
}
export interface _SERVICE {
  'addAdmin' : ActorMethod<[string], boolean>,
  'countUsers' : ActorMethod<[], bigint>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'isUsernameTaken' : ActorMethod<[string], boolean>,
  'login' : ActorMethod<[string, string], [] | [UserProfile]>,
  'register' : ActorMethod<[string, string, bigint], UpdateUserProfileResponse>,
  'removeUser' : ActorMethod<[string], boolean>,
  'updateCameraVerification' : ActorMethod<[string, boolean], boolean>,
  'updateDisplayName' : ActorMethod<[string, string], boolean>,
  'updateParentalControls' : ActorMethod<[string, boolean, bigint], boolean>,
  'updatePassword' : ActorMethod<[string, string, string], boolean>,
  'verifyAge' : ActorMethod<[string, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];